
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zalenium-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /zalenium
        backend:
          serviceName: zalenium
          servicePort: 4444

